# Generated by Django 4.2.8 on 2023-12-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='free_time',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='parking',
            name='max_parking_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='occupied_places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='price_per_minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='registry_nubmer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
