# Generated by Django 5.0 on 2023-12-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20)),
                ('card_num', models.PositiveBigIntegerField()),
                ('card_period', models.PositiveIntegerField()),
                ('card_cvv', models.PositiveIntegerField()),
                ('rights', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('coupon_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parking',
            name='free_time',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='parking',
            name='max_parking_spaces',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='parking',
            name='occupied_places',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='parking',
            name='price_per_minute',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='parking',
            name='registry_nubmer',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='parking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('benefit', models.BooleanField(default=False)),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkapp.parking')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkapp.user')),
            ],
        ),
    ]
