# Generated by Django 5.0 on 2023-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0002_user_parking_address_parking_free_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coupon_id',
        ),
        migrations.AddField(
            model_name='user',
            name='park_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rights',
            field=models.IntegerField(default=0),
        ),
    ]
