# Generated by Django 4.2.8 on 2023-12-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0002_reciept_final_price_alter_parking_free_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='final_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
