# Generated by Django 4.2.8 on 2023-12-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0004_alter_reciept_final_price_alter_reciept_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
