# Generated by Django 4.2.8 on 2023-12-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0005_alter_reciept_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='final_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='finish_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
