# Generated by Django 4.2.8 on 2023-12-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0006_alter_reciept_final_price_alter_reciept_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='final_price',
            field=models.BigIntegerField(default=-1),
        ),
    ]
